[package]
name = "perms"
version = "0.1.4"
edition = "2024"

[lib]
name = "perms"
path = "src/lib.rs"

[dependencies]
jsonwebtoken = "9.3.0"
serde = { version = "1.0", features = ["derive"] }
actix-web = "4.9.0"
mongodb = "3.2.3"